services:
  postgres:
    image: postgres:16
    container_name: todo-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tododb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: todo-backend
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    container_name: todo-frontend
    restart: always
    ports:
      - "5173:3000"
    depends_on:
      - backend

volumes:
  postgres_data: